import { NotificationChannel } from '../enums/notification-channel.enum.js';
import {
  NotificationTemplateCode,
  type NotificationTemplateCodeValue,
} from '../enums/notification-template.enum.js';

export interface DefaultNotificationTemplateDefinition {
  templateCode: NotificationTemplateCodeValue;
  name: string;
  channel: (typeof NotificationChannel)[keyof typeof NotificationChannel];
  subjectTemplate: string | null;
  bodyTemplate: string;
  isActive: boolean;
}

/**
 * 29 bildirim şablonu seed tanımı — içeriksiz metinler (hassas veri yok).
 */
export const DEFAULT_NOTIFICATION_TEMPLATES: readonly DefaultNotificationTemplateDefinition[] = [
  {
    templateCode: NotificationTemplateCode.TASK_ASSIGNED,
    name: 'Görev Atandı',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: 'Yeni göreviniz var',
    bodyTemplate: 'Size yeni bir görev atanmıştır. Detaylar için platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.TASK_COMPLETED,
    name: 'Görev Tamamlandı',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: 'Görev tamamlandı',
    bodyTemplate: 'İlgili görev tamamlanmıştır. Detaylar için platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.TASK_DELEGATED,
    name: 'Görev Devredildi',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: 'Görev devri',
    bodyTemplate: 'Size devredilen bir görev bulunmaktadır. Detaylar için platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.SLA_WARNING,
    name: 'SLA Uyarısı',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: 'SLA uyarısı',
    bodyTemplate: 'Bir görevinizin SLA süresi dolmak üzeredir. Platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.SLA_BREACH,
    name: 'SLA Aşımı',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: 'SLA aşımı',
    bodyTemplate: 'Bir görevinizin SLA süresi aşılmıştır. Platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.CASE_TRANSITION,
    name: 'Vaka Durumu Değişti',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: 'Vaka durumu güncellendi',
    bodyTemplate:
      'İlgili vakada durum değişikliği yapılmıştır. Detaylar için platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.SILENT_ACCEPTANCE_WARNING,
    name: 'Sessiz Kabul Uyarısı',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: 'Onay süresi dolmak üzere',
    bodyTemplate: 'Bekleyen bir onay kararınız bulunmaktadır. Platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.SILENT_ACCEPTANCE_CREATED,
    name: 'Sessiz Kabul Oluşturuldu',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: null,
    bodyTemplate: 'Sessiz kabul kaydı oluşturulmuştur. Detaylar için platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.DECISION_VOTE_REQUESTED,
    name: 'Karar Oyu Bekleniyor',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: 'Onayınız bekleniyor',
    bodyTemplate: 'Bir karar için onayınız beklenmektedir. Platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.ACTION_ASSIGNED,
    name: 'Aksiyon Atandı',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: 'Yeni aksiyon görevi',
    bodyTemplate: 'Size bir aksiyon görevi atanmıştır. Detaylar için platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.SECURE_MESSAGE_RECEIVED,
    name: 'Güvenli Mesaj Alındı',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: null,
    bodyTemplate: 'İlgili vakada yeni bir güvenli mesaj bulunmaktadır. Platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.SECURE_MESSAGE_REPORTER,
    name: 'Bildirimci Güvenli Mesaj',
    channel: NotificationChannel.SECURE_REPORTER_MESSAGE,
    subjectTemplate: null,
    bodyTemplate: 'Takip ekranınızda yeni bir mesajınız bulunmaktadır.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.RAPPORTEUR_ASSIGNED,
    name: 'Raportör Görevi Atandı',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: 'Raportör görevi',
    bodyTemplate: 'Yeni bir raportör görevi atanmıştır. Detaylar için platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.BOARD_VETO,
    name: 'HYKB Veto',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: null,
    bodyTemplate: 'HYKB tarafından veto uygulanmıştır. Detaylar için platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.BOARD_APPROVE,
    name: 'HYKB Onayı',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: null,
    bodyTemplate: 'HYKB onayı alınmıştır. Detaylar için platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.MEMBER_APPROVAL_REQUESTED,
    name: 'Üye Onayı Bekleniyor',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: 'Üye onayı',
    bodyTemplate: 'Kurul üyesi onayı beklenmektedir. Platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.MEMBER_OBJECTION,
    name: 'Üye İtirazı',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: null,
    bodyTemplate: 'Bir kurul üyesi itiraz bildirmiştir. Detaylar için platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.ACTION_RESPONSE_SUBMITTED,
    name: 'Aksiyon Yanıtı Gönderildi',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: null,
    bodyTemplate: 'Aksiyon yanıtı gönderilmiştir. Detaylar için platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.CASE_CLOSED,
    name: 'Vaka Kapatıldı',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: null,
    bodyTemplate: 'İlgili vaka kapatılmıştır. Detaylar için platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.DOCUMENT_QUARANTINED,
    name: 'Doküman Karantinada',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: null,
    bodyTemplate: 'Yüklenen bir doküman karantinaya alınmıştır. Platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.DOCUMENT_REJECTED,
    name: 'Doküman Reddedildi',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: null,
    bodyTemplate: 'Yüklenen bir doküman reddedilmiştir. Platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.DOCUMENT_SCAN_COMPLETE,
    name: 'Doküman Taraması Tamamlandı',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: null,
    bodyTemplate: 'Doküman taraması tamamlanmıştır. Platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.FOLLOW_UP_REASSIGNED,
    name: 'Takip Görevi Yeniden Atandı',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: null,
    bodyTemplate: 'Takip görevi yeniden atanmıştır. Detaylar için platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.IMPLEMENTATION_LETTER_READY,
    name: 'Uygulama Yazısı Hazır',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: null,
    bodyTemplate: 'Uygulama yazısı hazırlanmıştır. Detaylar için platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.PRE_RESEARCH_COMPLETED,
    name: 'Ön Araştırma Tamamlandı',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: null,
    bodyTemplate: 'Ön araştırma tamamlanmıştır. Detaylar için platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.CHAIR_GATE_DECISION,
    name: 'Başkan Kapısı Kararı',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: null,
    bodyTemplate: 'Kurul başkanı kapısı kararı verilmiştir. Platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.DECISION_DRAFT_READY,
    name: 'Karar Taslağı Hazır',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: null,
    bodyTemplate: 'Karar taslağı hazırlanmıştır. Detaylar için platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.TASK_OVERDUE_REMINDER,
    name: 'Geciken Görev Hatırlatması',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: 'Geciken görev',
    bodyTemplate: 'Geciken bir göreviniz bulunmaktadır. Platforma giriş yapınız.',
    isActive: true,
  },
  {
    templateCode: NotificationTemplateCode.APPROVAL_WORK_ITEM_ASSIGNED,
    name: 'Yapılandırma Onayı Bekliyor',
    channel: NotificationChannel.IN_APP,
    subjectTemplate: 'Bekleyen onay işi',
    bodyTemplate:
      'Bekleyen bir yapılandırma onayı bulunmaktadır. Detaylar için Görevlerim ekranına gidiniz.',
    isActive: true,
  },
] as const;
