export const ErrorCode = {
  AUTH_OIDC_FAILED: 'AUTH_OIDC_FAILED',
  AUTH_SESSION_REQUIRED: 'AUTH_SESSION_REQUIRED',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_BRUTE_FORCE_LOCKED: 'AUTH_BRUTE_FORCE_LOCKED',
  AUTH_INVALID_RETURN_URL: 'AUTH_INVALID_RETURN_URL',
  AUTH_CSRF_INVALID: 'AUTH_CSRF_INVALID',
  AUTHZ_FORBIDDEN: 'AUTHZ_FORBIDDEN',
  AUTHZ_NOT_FOUND: 'AUTHZ_NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CRYPTO_DECRYPT_FAILED: 'CRYPTO_DECRYPT_FAILED',
  CRYPTO_KMS_UNAVAILABLE: 'CRYPTO_KMS_UNAVAILABLE',
  CRYPTO_INVALID_KEY_CONFIG: 'CRYPTO_INVALID_KEY_CONFIG',
  AUDIT_FORBIDDEN_CONTENT: 'AUDIT_FORBIDDEN_CONTENT',
  AUDIT_PUBLISH_FAILED: 'AUDIT_PUBLISH_FAILED',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
