export const ErrorCode = {
  AUTH_OIDC_FAILED: 'AUTH_OIDC_FAILED',
  AUTH_SESSION_REQUIRED: 'AUTH_SESSION_REQUIRED',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_BRUTE_FORCE_LOCKED: 'AUTH_BRUTE_FORCE_LOCKED',
  AUTH_INVALID_RETURN_URL: 'AUTH_INVALID_RETURN_URL',
  AUTH_CSRF_INVALID: 'AUTH_CSRF_INVALID',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
