/**
 * Notification event types — Faz 8 outbox event_type; template_code ile eşleşir (notification-event-template-map).
 */
export const NotificationEventType = {
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_DELEGATED: 'TASK_DELEGATED',
  SLA_WARNING: 'SLA_WARNING',
  SLA_BREACH: 'SLA_BREACH',
  CASE_TRANSITION: 'CASE_TRANSITION',
  SILENT_ACCEPTANCE_WARNING: 'SILENT_ACCEPTANCE_WARNING',
  SILENT_ACCEPTANCE_CREATED: 'SILENT_ACCEPTANCE_CREATED',
  DECISION_VOTE_REQUESTED: 'DECISION_VOTE_REQUESTED',
  ACTION_ASSIGNED: 'ACTION_ASSIGNED',
  SECURE_MESSAGE_RECEIVED: 'SECURE_MESSAGE_RECEIVED',
  SECURE_MESSAGE_REPORTER: 'SECURE_MESSAGE_REPORTER',
  RAPPORTEUR_ASSIGNED: 'RAPPORTEUR_ASSIGNED',
  BOARD_VETO: 'BOARD_VETO',
  BOARD_APPROVE: 'BOARD_APPROVE',
  MEMBER_APPROVAL_REQUESTED: 'MEMBER_APPROVAL_REQUESTED',
  MEMBER_OBJECTION: 'MEMBER_OBJECTION',
  ACTION_RESPONSE_SUBMITTED: 'ACTION_RESPONSE_SUBMITTED',
  CASE_CLOSED: 'CASE_CLOSED',
  DOCUMENT_QUARANTINED: 'DOCUMENT_QUARANTINED',
  DOCUMENT_REJECTED: 'DOCUMENT_REJECTED',
  DOCUMENT_SCAN_COMPLETE: 'DOCUMENT_SCAN_COMPLETE',
  FOLLOW_UP_REASSIGNED: 'FOLLOW_UP_REASSIGNED',
  IMPLEMENTATION_LETTER_READY: 'IMPLEMENTATION_LETTER_READY',
  PRE_RESEARCH_COMPLETED: 'PRE_RESEARCH_COMPLETED',
  CHAIR_GATE_DECISION: 'CHAIR_GATE_DECISION',
  DECISION_DRAFT_READY: 'DECISION_DRAFT_READY',
  TASK_OVERDUE_REMINDER: 'TASK_OVERDUE_REMINDER',
  APPROVAL_WORK_ITEM_ASSIGNED: 'APPROVAL_WORK_ITEM_ASSIGNED',
} as const;

export type NotificationEventTypeCode =
  (typeof NotificationEventType)[keyof typeof NotificationEventType];

export const NOTIFICATION_EVENT_TYPE_VALUES = Object.values(
  NotificationEventType,
) as readonly NotificationEventTypeCode[];
